
Ryan@RJ MINGW64 ~/Desktop (master)
$ cd ~/Documents

Ryan@RJ MINGW64 ~/Documents
$ ls
 Coding_Dojo/                       hp.system.package.metadata/   SoftMaker/
'Custom Office Templates'/         'My Music'@                    Zoom/
 desktop.ini                       'My Pictures'@
 hp.applications.package.appdata/  'My Videos'@

Ryan@RJ MINGW64 ~/Documents
$ cd coding_dojo

Ryan@RJ MINGW64 ~/Documents/coding_dojo
$ ls
 academy-pacman-master/   Demo/     Javascript/
'API and AJAX'/           Github/   Jquery/
'API weather demo'/       HTML/     python_stack/

Ryan@RJ MINGW64 ~/Documents/coding_dojo
$ cd pyhon_stack
bash: cd: pyhon_stack: No such file or directory

Ryan@RJ MINGW64 ~/Documents/coding_dojo
$ cd python_stack

Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack
$ ls
django/  done.txt  my_environments/  mysql/  python/

Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack
$ cd django

Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django
$ ls
django_extras/      django_fundamentals/  django_orm/
django_full_stack/  django_intro/

Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django
$ cd ..

Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack
$ cd my_environments

Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/my_environments
$ ls
djangoPy3Env/  py3Env/

Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/my_environments
$ source djangoPy3Env/scripts/activate
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/my_environments
$ ls
djangoPy3Env/  py3Env/
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/my_environments
$ cd ..
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack
$ cd django
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django
$ cd django_intro
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro
$ ls
dojo_ninjas_project/   ninja_gold_project/             single_model_orm/
dojo_survey_project/   random_word_generator_project/  time_display_project/
first_django_project/  simple_django_project/
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro
$ cd dojo_ninjas_project
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ ls
db.sqlite3  dojo_ninjas_app/  dojo_ninjas_project/  manage.py*
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ code .
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Ryan James\Documents\Coding_Dojo\python_stack\my_environments\d
jangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 381, in
execute_from_command_line
    utility.execute()
  File "C:\Users\Ryan James\Documents\Coding_Dojo\python_stack\my_environments\d
jangoPy3Env\lib\site-packages\django\core\management\__init__.py", line 357, in
execute
    django.setup()
  File "C:\Users\Ryan James\Documents\Coding_Dojo\python_stack\my_environments\d
jangoPy3Env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Ryan James\Documents\Coding_Dojo\python_stack\my_environments\d
jangoPy3Env\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Ryan James\Documents\Coding_Dojo\python_stack\my_environments\d
jangoPy3Env\lib\site-packages\django\apps\config.py", line 211, in import_models

    self.models_module = import_module(models_module_name)
  File "C:\Users\Ryan James\AppData\Local\Programs\Python\Python38\lib\importlib
\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Ryan James\Documents\coding_dojo\python_stack\django\django_int
ro\dojo_ninjas_project\dojo_ninjas_app\models.py", line 3, in <module>
    class Dojo(models.Model):
  File "C:\Users\Ryan James\Documents\coding_dojo\python_stack\django\django_int
ro\dojo_ninjas_project\dojo_ninjas_app\models.py", line 6, in Dojo
    state = models.Charfield(max_length=2)
AttributeError: module 'django.db.models' has no attribute 'Charfield'
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py makemigrations
Migrations for 'dojo_ninjas_app':
  dojo_ninjas_app\migrations\0001_initial.py
    - Create model Dojo
    - Create model Ninja
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dojo_ninjas_app, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying dojo_ninjas_app.0001_initial... OK
  Applying sessions.0001_initial... OK
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py shell
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AM
D64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from dojo_ninjas_app.models import Dojo, Ninja

In [2]: Dojo.objects.create(name="Zen",city="Kirkland",state="WA")
Out[2]: <Dojo: Dojo object (1)>

In [3]: Dojo.objects.create(name="Elixir",city="Los Angeles",state="CA")
Out[3]: <Dojo: Dojo object (2)>

In [4]: Dojo.objects.create(name="Lumen",city="Springdale",state="UT")
Out[4]: <Dojo: Dojo object (3)>

In [5]: dojo1 = Dojo.objects.get(id=1)

In [6]: dojo1.name
Out[6]: 'Zen'

In [7]: dojo1.delete()
Out[7]: (1, {'dojo_ninjas_app.Ninja': 0, 'dojo_ninjas_app.Dojo': 1})

In [8]: dojo1.name
Out[8]: 'Zen'

In [9]: dojo2 = Dojo.objects.get(id=2)

In [10]: dojo2.nam
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-9427d847e356> in <module>
----> 1 dojo2.nam

AttributeError: 'Dojo' object has no attribute 'nam'

In [11]: dojo2.name
Out[11]: 'Elixir'

In [12]: dojo2.delete()
Out[12]: (1, {'dojo_ninjas_app.Ninja': 0, 'dojo_ninjas_app.Dojo': 1})

In [13]: Dojo.objects.all()
Out[13]: <QuerySet [<Dojo: Dojo object (3)>]>

In [14]: dojo3 = Dojo.objects.get(id=3)

In [15]: dojo3.delete()
Out[15]: (1, {'dojo_ninjas_app.Ninja': 0, 'dojo_ninjas_app.Dojo': 1})

In [16]: Dojo.objects.all()
Out[16]: <QuerySet []>

In [17]: Dojo.objects.create(name="Zen",city="Kirkland",state="WA")
Out[17]: <Dojo: Dojo object (4)>

In [18]: Dojo.objects.create(name="Elixir",city="Los Angeles",state="CA")
Out[18]: <Dojo: Dojo object (5)>

In [19]: Dojo.objects.create(name="Lumen",city="Springdale",state="UT")
Out[19]: <Dojo: Dojo object (6)>

In [20]: Zen = Dojo.objects.get(id=4)

In [21]: Zen.name
Out[21]: 'Zen'

In [22]: Elixir = Dojo.objects.get(id=5)

In [23]: Elixir.name
Out[23]: 'Elixir'

In [24]: Lumen = Dojo.objects.get(id=6)

In [25]: Luman.name
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-25-3574b59a4b01> in <module>
----> 1 Luman.name

NameError: name 'Luman' is not defined

In [26]: Lumen.name
Out[26]: 'Lumen'

In [27]: Ninja.models.create(first_name="Ryan",last_name="Delabahan",dojo="Zen"
    ...: )
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-c51422ae8595> in <module>
----> 1 Ninja.models.create(first_name="Ryan",last_name="Delabahan",dojo="Zen")

AttributeError: type object 'Ninja' has no attribute 'models'

In [28]:  Ninja.objects.create(first_name="Ryan",last_name="Delabahan",dojo="Ze
    ...: n")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-4f073884f757> in <module>
----> 1 Ninja.objects.create(first_name="Ryan",last_name="Delabahan",dojo="Zen")


~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\manager.py in manager_method(self, *args, **kwargs)
     80         def create_method(name, method):
     81             def manager_method(self, *args, **kwargs):
---> 82                 return getattr(self.get_queryset(), name)(*args, **kwarg
s)
     83             manager_method.__name__ = method.__name__
     84             manager_method.__doc__ = method.__doc__

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\query.py in create(self, **kwargs)
    418         and returning the created object.
    419         """
--> 420         obj = self.model(**kwargs)
    421         self._for_write = True
    422         obj.save(force_insert=True, using=self.db)

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\base.py in __init__(self, *args, **kwargs)
    481                 # checked) by the RelatedObjectDescriptor.
    482                 if rel_obj is not _DEFERRED:
--> 483                     _setattr(self, field.name, rel_obj)
    484             else:
    485                 if val is not _DEFERRED:

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\fields\related_descriptors.py in __set__(self, instance, va
lue)
    204         # An object must be an instance of the related class.
    205         if value is not None and not isinstance(value, self.field.remote
_field.model._meta.concrete_model):
--> 206             raise ValueError(
    207                 'Cannot assign "%r": "%s.%s" must be a "%s" instance.' %
 (
    208                     value,

ValueError: Cannot assign "'Zen'": "Ninja.dojo" must be a "Dojo" instance.

In [29]: Ninja.objects.create(first_name="Ryan",last_name="Delabahan",dojo="Zen
    ...: ")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-4f073884f757> in <module>
----> 1 Ninja.objects.create(first_name="Ryan",last_name="Delabahan",dojo="Zen")


~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\manager.py in manager_method(self, *args, **kwargs)
     80         def create_method(name, method):
     81             def manager_method(self, *args, **kwargs):
---> 82                 return getattr(self.get_queryset(), name)(*args, **kwarg
s)
     83             manager_method.__name__ = method.__name__
     84             manager_method.__doc__ = method.__doc__

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\query.py in create(self, **kwargs)
    418         and returning the created object.
    419         """
--> 420         obj = self.model(**kwargs)
    421         self._for_write = True
    422         obj.save(force_insert=True, using=self.db)

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\base.py in __init__(self, *args, **kwargs)
    481                 # checked) by the RelatedObjectDescriptor.
    482                 if rel_obj is not _DEFERRED:
--> 483                     _setattr(self, field.name, rel_obj)
    484             else:
    485                 if val is not _DEFERRED:

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\fields\related_descriptors.py in __set__(self, instance, va
lue)
    204         # An object must be an instance of the related class.
    205         if value is not None and not isinstance(value, self.field.remote
_field.model._meta.concrete_model):
--> 206             raise ValueError(
    207                 'Cannot assign "%r": "%s.%s" must be a "%s" instance.' %
 (
    208                     value,

ValueError: Cannot assign "'Zen'": "Ninja.dojo" must be a "Dojo" instance.

In [30]: Zen1 = Dojo.objects.get(id=4)

In [31]: Zen1.name
Out[31]: 'Zen'

In [32]: Zen.name
Out[32]: 'Zen'

In [33]: Ninja.models.create(first_name="Ryan",last_name="Delabahan",dojo="Zen1
    ...: ")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-1181f88ab75f> in <module>
----> 1 Ninja.models.create(first_name="Ryan",last_name="Delabahan",dojo="Zen1")


AttributeError: type object 'Ninja' has no attribute 'models'

In [34]: Ninja.objects.create(first_name="Ryan",last_name="Delabahan",dojo="Zen
    ...: 1")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-34-ca6b67c7526b> in <module>
----> 1 Ninja.objects.create(first_name="Ryan",last_name="Delabahan",dojo="Zen1"
)

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\manager.py in manager_method(self, *args, **kwargs)
     80         def create_method(name, method):
     81             def manager_method(self, *args, **kwargs):
---> 82                 return getattr(self.get_queryset(), name)(*args, **kwarg
s)
     83             manager_method.__name__ = method.__name__
     84             manager_method.__doc__ = method.__doc__

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\query.py in create(self, **kwargs)
    418         and returning the created object.
    419         """
--> 420         obj = self.model(**kwargs)
    421         self._for_write = True
    422         obj.save(force_insert=True, using=self.db)

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\base.py in __init__(self, *args, **kwargs)
    481                 # checked) by the RelatedObjectDescriptor.
    482                 if rel_obj is not _DEFERRED:
--> 483                     _setattr(self, field.name, rel_obj)
    484             else:
    485                 if val is not _DEFERRED:

~\Documents\Coding_Dojo\python_stack\my_environments\djangoPy3Env\lib\site-packa
ges\django\db\models\fields\related_descriptors.py in __set__(self, instance, va
lue)
    204         # An object must be an instance of the related class.
    205         if value is not None and not isinstance(value, self.field.remote
_field.model._meta.concrete_model):
--> 206             raise ValueError(
    207                 'Cannot assign "%r": "%s.%s" must be a "%s" instance.' %
 (
    208                     value,

ValueError: Cannot assign "'Zen1'": "Ninja.dojo" must be a "Dojo" instance.

In [35]: Ninja.models.create(first_name="Ryan",last_name="Delabahan",dojo=Zen)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-1422f9cafcb0> in <module>
----> 1 Ninja.models.create(first_name="Ryan",last_name="Delabahan",dojo=Zen)

AttributeError: type object 'Ninja' has no attribute 'models'

In [36]: Ninja.objects.create(first_name="Ryan",last_name="Delabahan",dojo=Zen)
    ...:
Out[36]: <Ninja: Ninja object (1)>

In [37]: Ninja.objects.create(first_name="Victoria",last_name="Cornell",dojo=Ze
    ...: n)
Out[37]: <Ninja: Ninja object (2)>

In [38]: Ninja.objects.create(first_name="Panda",last_name="Express",dojo=Zen)
Out[38]: <Ninja: Ninja object (3)>

In [39]: Ninja.objects.create(first_name="Zack",last_name="James",dojo=Elixir)
Out[39]: <Ninja: Ninja object (4)>

In [40]: Ninja.objects.create(first_name="Manu",last_name="Ginobili",dojo=Elixi
    ...: r)
Out[40]: <Ninja: Ninja object (5)>

In [41]: Ninja.objects.create(first_name="Tony",last_name="Parker",dojo=Elixir)
    ...:
Out[41]: <Ninja: Ninja object (6)>

In [42]:
    ...: Ryan@RJ MINGW64 ~/Desktop (master)
    ...: $ cd ~/Documents
    ...:
  File "<ipython-input-42-2a47f6947716>", line 1
    Ryan@RJ MINGW64 ~/Desktop (master)
            ^
SyntaxError: invalid syntax


In [43]: Ryan@RJ MINGW64 ~/Documents
    ...: $ ls
    ...:  Coding_Dojo/                       hp.system.package.metadata/   Soft
    ...: Maker/
    ...: 'Custom Office Templates'/         'My Music'@                    Zoom
    ...: /
    ...:  desktop.ini                       'My Pictures'@
    ...:  hp.applications.package.appdata/  'My Videos'@
    ...:
  File "<ipython-input-43-6367b79765f4>", line 1
    Ryan@RJ MINGW64 ~/Documents
            ^
SyntaxError: invalid syntax


    ...: <ipython-input-33-1181f88ab75f> in <module>
In [44]:  Ninja.objects.create(first_name="Issei",last_name="Hori",dojo=Lumen)
Out[44]: <Ninja: Ninja object (7)>

In [45]: Ninja.objects.create(first_name="Yuki",last_name="Kyushu",dojo=Lumen)
Out[45]: <Ninja: Ninja object (8)>

In [46]: Ninja.objects.create(first_name="2goo",last_name="FNC",dojo=Lumen)
Out[46]: <Ninja: Ninja object (9)>

    ...:  desktop.ini                       'My Pictures'@
    ...:  hp.applications.package.appdata/  'My Videos'@
    ...:
    ...: Ryan@RJ MINGW64 ~/Documents
    ...: $ cd coding_dojo
    ...:
    ...: Ryan@RJ MINGW64 ~/Documents/coding_dojo
    ...: $ ls
    ...:  academy-pacman-master/   Demo/     Javascript/
    ...: 'API and AJAX'/           Github/   Jquery/
    ...: 'API weather demo'/       HTML/     python_stack/
    ...:
    ...: Ryan@RJ MINGW64 ~/Documents/coding_dojo
    ...: $ cd pyhon_stack
    ...: bash: cd: pyhon_stack: No such file or directory
    ...:
    ...: Ryan@RJ MINGW64 ~/Documents/coding_dojo
    ...: $ cd python_stack
    ...:
    ...: Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack
    ...: $ ls
    ...: django/  done.txt  my_environments/  mysql/  python/
    ...:
  File "<ipython-input-47-e4f72cbeaf32>", line 1
    Ryan@RJ MINGW64 ~/Desktop (master)
            ^
SyntaxError: invalid syntax


In [48]: Dojo.ninjas.all()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-48-5284e1c4a6b9> in <module>
----> 1 Dojo.ninjas.all()

AttributeError: 'ReverseManyToOneDescriptor' object has no attribute 'all'

In [49]: Dojo.Zen.all()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-49-fb2be885c250> in <module>
----> 1 Dojo.Zen.all()

AttributeError: type object 'Dojo' has no attribute 'Zen'

In [50]: Zen.ninjas.all()
Out[50]: <QuerySet [<Ninja: Ninja object (1)>, <Ninja: Ninja object (2)>, <Ninja
: Ninja object (3)>]>

In [51]: Zen.ninjas.get(id=1).name
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-51-0285e18478cb> in <module>
----> 1 Zen.ninjas.get(id=1).name

AttributeError: 'Ninja' object has no attribute 'name'

In [52]: Zen.ninjas.get(id="1")
Out[52]: <Ninja: Ninja object (1)>

In [53]: Zen.ninjas.get(id=1).first_name
Out[53]: 'Ryan'

In [54]: Elixir.ninjas.all()
Out[54]: <QuerySet [<Ninja: Ninja object (4)>, <Ninja: Ninja object (5)>, <Ninja
: Ninja object (6)>]>

In [55]: Lumen.ninjas.all()
Out[55]: <QuerySet [<Ninja: Ninja object (7)>, <Ninja: Ninja object (8)>, <Ninja
: Ninja object (9)>]>

In [56]: Lumen.ninjas.getlast()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-56-21d128577186> in <module>
----> 1 Lumen.ninjas.getlast()

AttributeError: 'RelatedManager' object has no attribute 'getlast'

In [57]: Lumen.ninjas.last()
Out[57]: <Ninja: Ninja object (9)>

In [58]: Lumen.ninjas.filter(id=9)
Out[58]: <QuerySet [<Ninja: Ninja object (9)>]>

In [59]: Lumen.ninjas.filter(first_name="Issei")
Out[59]: <QuerySet [<Ninja: Ninja object (7)>]>

In [60]: exit()
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py makemigrations
You are trying to add a non-nullable field 'description' to dojo without a defau
lt; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null
value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 2
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py makemigrations
Migrations for 'dojo_ninjas_app':
  dojo_ninjas_app\migrations\0002_dojo_description.py
    - Add field description to dojo
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dojo_ninjas_app, sessions
Running migrations:
  Applying dojo_ninjas_app.0002_dojo_description... OK
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py makemigrations
Migrations for 'dojo_ninjas_app':
  dojo_ninjas_app\migrations\0003_auto_20201110_1239.py
    - Alter field description on dojo
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dojo_ninjas_app, sessions
Running migrations:
  Applying dojo_ninjas_app.0003_auto_20201110_1239... OK
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ Zen.description
bash: Zen.description: command not found
(djangoPy3Env)
Ryan@RJ MINGW64 ~/Documents/coding_dojo/python_stack/django/django_intro/dojo_ninjas_project
$ python manage.py shell
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AM
D64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from dojo_ninjas_app.models import Dojo, Ninja

In [2]: Zen.name
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-0de31dee09d3> in <module>
----> 1 Zen.name

NameError: name 'Zen' is not defined

In [3]: Dojo.objects.all()
Out[3]: <QuerySet [<Dojo: Dojo object (4)>, <Dojo: Dojo object (5)>, <Dojo: Dojo
 object (6)>]>

In [4]: Zen = Dojo.objects.get(id=4)

In [5]: Zen.name
Out[5]: 'Zen'

In [6]: Zen.description
Out[6]: 'old dojo'

In [7]: Dojo.objects.create(name="Zion",city="San Diego",state="CA",description
   ...: ="Legendary Dojo!!!")
Out[7]: <Dojo: Dojo object (7)>

In [8]: Zion = Dojo.objects.get(id=7)

In [9]: Zion.name
Out[9]: 'Zion'

In [10]: Zion.city
Out[10]: 'San Diego'

In [11]: Zion.state
Out[11]: 'CA'

In [12]: Zion.description
Out[12]: 'Legendary Dojo!!!'

In [13]:
